racer: basic logic to check website duration
- this talks to real websites and this is not ideal as its a cause of a
  flaky test. We are not controlling what happens out in the internet
  wild.
- the test may or may not pass

```
➜ gopher_zone/11_select main ✗ (?) go test -cover -v
=== RUN   TestRacer
    racer_test.go:13: got "http://www.facebook.com" want "http://www.quii.dev"
--- FAIL: TestRacer (2.35s)
FAIL
coverage: 88.9% of statements
exit status 1
FAIL	gopher_zone/11_select	4.375s
```