convert: use property based testing
- introduce property based testing
- test against properties and not examples as we have had before
- this test already fails since we can not convert a negative number

```
=== RUN   TestPropertiesOfConversion
    roman_numerals_test.go:83: failed checks #1: failed on input -2027542302380675068
--- FAIL: TestPropertiesOfConversion (0.00s)
```