generics: see the danger of using interface{}
- the compiler is not helpful because we are not specific on the types
  passed to the function.
- test compiles and fails although the although the error message is
  unclear.

  ```
  ➜ gopher_zone/19_generics main ✓ go test -cover -v
=== RUN   TestAssertFunctions
=== RUN   TestAssertFunctions/assert_on_integers
=== RUN   TestAssertFunctions/assert_on_strings
=== RUN   TestAssertFunctions/assert_different_types
    generics_test.go:23: got 1 want 1
--- FAIL: TestAssertFunctions (0.00s)
    --- PASS: TestAssertFunctions/assert_on_integers (0.00s)
    --- PASS: TestAssertFunctions/assert_on_strings (0.00s)
    --- FAIL: TestAssertFunctions/assert_different_types (0.00s)
FAIL
  ```
- this code will most likely surface run time error and make our end
  users suffer.